spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/${MYDATABASE}
    username: ${MYUSERNAME}
    password: ${MYPASSWORD}
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
    open-in-view: false
    defer-datasource-initialization: true
    show-sql: false
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  messages:
    basename:
      - messages
      - errors

logo:
  dir: /Users/jun-yeongchoe/Desktop/project/ServiceHub/src/main/resources/image/

profile:
  dir: /Users/jun-yeongchoe/Desktop/project/ServiceHub/src/main/resources/profile/

customer:
  clientId: ${CLIENTID}
  server: https://impati-customer.com

server:
  port: 8079
