name: Prod-Stage CD

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Clone code from repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'

      - name: before script executable
        run: chmod 755 scripts/before.sh

      - name: Run before script
        run: ./scripts/before.sh

      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
        with:
          arguments: bootJar

      - name: Let script executable
        run: chmod 755 scripts/run.sh

      - name: Run java application
        run: ./scripts/run.sh
        env:
          RUNNER_TRACKING_ID: ""
          PROD_CLIENT_ID: ${{secrets.PROD_CLIENT_ID}}
          PROD_SERVER_PORT: ${{secrets.PROD_SERVER_PORT}}
          DB_HOST: ${{secrets.DB_HOST}}
          DB_PORT: ${{secrets.DB_PORT}}
          DB_NAME: ${{secrets.DB_NAME}}
          DB_USER: ${{secrets.DB_USER}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          HOME_DIR: ${{secrets.HOME_DIR}}

